### PR TITLE
add dockerfile

### PR DESCRIPTION
**Pull request by alisoam**
docker image to use in gitlab ci

### CODE REVIEW

**Comment by s-soroosh** [comment]
Hi @AliSoAm ,

Thank you so much for the contribution. I'll merge this PR once we implemented the required pipeline to release new version to the docker hub on every release.

**Comment by alisoam** [comment]
If you want to use travis-ci I can write .travis.yml too.

**Comment by s-soroosh** [comment]
@AliSoAm Yes we do use travis. 
Awesome we would be more than happy you do so. 

Thank you so much

**Comment by s-soroosh** [comment]
Hi @AliSoAm,

Thank you so much for the time you put on contributing in the project. 
Do you have Twitter handle? We usually tweet about the people who contribute in Fandogh. 
Would be nice to mention your handle in the tweet :)

**Comment by alisoam** [comment]
Hi @psycho-ir
You merged it before I finished it :). I finished it just now. My goal was to automate the deployment for docker and pypi. If you push a version tag it would automatically change the VERSION in __init__.py to tag name and deploy on docker and pypi. But I think you prefer other ways.

**Comment by s-soroosh** [comment]
@AliSoAm, 
We are open to any way that makes more sense. 
Plz don't hesitate to open the PR again, so we see which one makes our lives easier.
Just found some time today to run a working version, so you can already pull the image from docker hub.

Thanks again

**Pull request merged**
